config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'     
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
    
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end
  root 'home#index'
  resources :groups
  resources :expenses
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Expense, author: user
    can :manage, Group, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups, dependent: :destroy

  validates :name, :amount, presence: true, length: { maximum: 255 }
  validates :amount, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }

  def total_amount
    expenses.sum('amount')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :name, :email, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource

  def index
    redirect_to groups_url
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense.groups.first, notice: 'Expense was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    flash[:success] = 'Expense was successfully deleted.'
    redirect_to groups_url
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # load_and_authorize_resource

  def index
    @groups = current_user.groups.order(:name)
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @expenses = @group.expenses.order('created_at DESC')
  end

  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Category was successfully destroyed!.' }
    end
  end

  private

  def set_group
    @group = Group.includes(:expenses).find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_expense.html.erb
<div class="container card mb-4">
	<div class="p-4">
		<div class="d-flex justify-content-between flex-column">
			<h5><%= expense.name %></h5>
			<small>$<%= expense.amount.round(2) %></small>
			<%= button_to "Delete", expense_path(expense), :method => :delete, :class => "btn btn-danger btn-sm"%>
		</div>
		<small class='text-muted'><%= expense.created_at.strftime("%d %b %Y") %></small>
	</div>
</div>

app/views/expenses/_form.html.erb
  <%= form_with(model: expense) do |form| %>
    <div>
      <h5 class='text-center display-6'>Add new transaction</h5>
    </div>
    <%= render "devise/shared/error_messages", resource: expense %>
    <div class="container">
      <%= form.text_field :name, autofocus: true, placeholder: "Name", class: "form-control m-2", required: true %>
      <%= form.number_field :amount, placeholder: "Amount", class: "form-control  m-2", required: true, step: 'any' %>
      <%= form.collection_select :group_ids, current_user.groups.order(:name), :id, :name, {}, { class: "form-select  m-2", multiple: true, required: true } %>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
      <%= form.submit "Save", class: "btn btn-success" %>
    </div>
  <% end %>

app/views/expenses/_index.html.erb
<div class="container">
<%= render @expenses %>
</div>

app/views/expenses/new.html.erb
<%= render 'form', expense: @expense %>

app/views/groups/_categories.html.erb
<% if @groups.any?%>
<% @groups.each do |group| %>
  <div class="card mb-3 p-2 container">
    <div class="row">
      <div class="col">
        
      </div>
      <div class="col d-flex justify-content-evenly flex-column">
          <h5 class="card-title "><%= link_to group.name, group_path(group), class: "text-decoration-none" %></h5>
          <p class="card-text"><small class="text-muted fs-6"><%= group.created_at.strftime("%d-%b-%Y")%></small></p>
      </div>
      <div class="col d-flex justify-content-evenly flex-column">
        <p> $<%= group.expenses.sum(:amount)%></p>
        <%if can? :destroy, group %>
          <%= button_to "Delete", group_path(group), method: :delete, class:"btn btn-danger btn-sm" %>
        <%end%>
      </div>
    </div>
  </div>
<%end%>
<%else%>
  <p class="p-2 m-2 h3">No category added!!!</p>
<%end%>

app/views/groups/_new_category_form.html.erb
<%= form_with(model: @group) do |form| %>
  <div class="container">

      <div class='pb-2'>
        <h5 class='text-center display-6'>Add a new category </h5>
      </div>
    <div class="m-3">
      <%= form.text_field :name, autofocus: true, placeholder: "Name", class: "form-control", required: true %>
    </div>
    <div class="m-3">
      <%= form.text_field :icon, placeholder: "Image Url", class: "form-control", required: true %>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
      <%= form.submit "Save", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<h1 class="text-center"> Categories </h1>
<div class="container">
  <%= render 'categories' %>
</div>

<footer class="footer">
  <div class="d-grid gap-2">
    <%= link_to "Add a new category", new_group_path, class: "btn btn-success border-radius-none" %>
  </div>
</footer>

app/views/groups/new.html.erb
<%= render 'new_category_form', group: @group %>

app/views/groups/show.html.erb
<div class="containers">
  <h5 class='text-center display-6'>TRANSACTION</h5>
  <div class="container p-4 pd-0 d-flex justify-content-between">
		<h5 class="fw-bold">Total Amount:</h5>
		<p class="fw-bold">$<%= @group.total_amount.round(2) %></p>
  </div>
  <div class="p-4 pt-0">
    
    <p class="text-muted text-end pt-2"><%= @group.name %></p>
  </div>
</div>
  <div class="divider mb-2"></div>
	  <%= render 'expenses/index', locals: { expenses: @expenses } %>
  </div>

<footer class="footer">
  <div class="d-grid gap-2">
    <%= link_to "Add new transaction", new_expense_path, class: "btn btn-success border-radius-none" %>
    <%= link_to 'Back', :back ,class: "btn btn-success border-radius-none"%>

  </div>
</footer>

app/views/home/index.html.erb
<div class="background-layout">
    <div class="container">
        <div class="text-center">
            <h1>Budgetprüfer</h1>
        </div>
    </div>
        
    <div class="row">
    <%= link_to 'Log in', user_session_path, class: 'btn btn-info text-nowrap row', style: 'background-color:#2596be;color:white' %>
  
          
    </div>

    <div class="row">
      <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success text-nowrap row', style: 'background-color:white;color:black' %>
           
    </div>
                   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <%= stylesheet_link_tag "style" , "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
  </head>

  <body>
  <%= render "navbar/navbar" %>
  
    <%= yield %>
    <script src="https://kit.fontawesome.com/b331332bf9.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/navbar/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-expand-sm navbar-light bg-primary">
    <div class="container-fluid">
        <% if current_page?(root_path) %>
            <a class="navbar-brand text-white" href="#">Welcome <%= current_user.name %> !</a>
        <% else %>
            <%= link_to root_path do %>
            <a class="navbar-brand text-white" href="#">Budget App</a>
            <% end %>
            <p><%= '' %></p>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Home', root_path, :class=>"nav-link active text-white"%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link text-white'%>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <div class="messages">
        <% if notice.to_s != '' %>
            <div class="alert alert-primary" role="alert"><%= notice %></div>
        <% end %>
        <% if alert.to_s != '' %>
            <div class="alert alert-danger" role="alert"><%= alert %></div>
        <% end %>
    </div>
<% end %>


       